// tests/contracts/mcp-manifest-fresh.test.mjs
//
// Systemic drift guard for the public /docs/mcp catalog (src/pages/docs/mcp.astro),
// which renders src/lib/mcp-manifest.json. That manifest is generated by parsing
// supabase/functions/nucleo-mcp/index.ts (mcp.tool() registrations) and is committed
// to the repo — so it goes stale the moment a tool is added/removed without re-running
// the generator. It silently drifted 312 -> 330 between 2026-06-08 and 2026-06-29
// (the /docs/mcp staleness this guard exists to prevent).
//
// Why a CI test and not a cron: both the source of truth (index.ts) and the rendered
// artifact (mcp-manifest.json) live in the repo, so drift is detectable at PR time with
// zero infra — no live-DB poll, no scheduled job. (A cron is the right tool only for
// drift against state that lives OUTSIDE the repo.)
//
// To fix a failure: node scripts/generate-mcp-manifest.mjs && git add src/lib/mcp-manifest.json

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { buildManifest, SOURCE_PATH, OUTPUT_PATH } from '../../scripts/generate-mcp-manifest.mjs';

const FIX = `Run: node scripts/generate-mcp-manifest.mjs && git add ${OUTPUT_PATH}`;

test('/docs/mcp manifest is in sync with nucleo-mcp index.ts (no tool drift)', () => {
  const text = readFileSync(SOURCE_PATH, 'utf8');
  const { body, duplicates } = buildManifest(text);
  const onDisk = JSON.parse(readFileSync(OUTPUT_PATH, 'utf8'));
  const { generated_at, ...onDiskBody } = onDisk;

  assert.equal(
    typeof generated_at,
    'string',
    `mcp-manifest.json must carry a generated_at timestamp. ${FIX}`
  );
  assert.equal(
    duplicates.length,
    0,
    `index.ts registers duplicate mcp.tool() names: ${duplicates.join(', ')}`
  );
  assert.equal(
    onDiskBody.total,
    body.total,
    `mcp-manifest.json total=${onDiskBody.total} but index.ts has ${body.total} ` +
      `mcp.tool() registrations. ${FIX}`
  );
  // Full structural equality (counts, domains, permissions, every tool entry).
  assert.deepEqual(
    onDiskBody,
    body,
    `mcp-manifest.json is stale vs index.ts (tool list/domains/permissions drifted). ${FIX}`
  );
});

test('mcp-manifest total equals the sum of per-permission and per-domain buckets', () => {
  const onDisk = JSON.parse(readFileSync(OUTPUT_PATH, 'utf8'));
  const permSum = Object.values(onDisk.by_permission).reduce((a, b) => a + b, 0);
  const domSum = Object.values(onDisk.by_domain).reduce((a, b) => a + b, 0);
  assert.equal(permSum, onDisk.total, 'by_permission buckets must sum to total');
  assert.equal(domSum, onDisk.total, 'by_domain buckets must sum to total');
  assert.equal(onDisk.tools.length, onDisk.total, 'tools array length must equal total');
});
