-- ============================================================================
-- DEPRECATED — see `20260723000000_baseline_rpcs_after_schema.sql`
--
-- This file was originally placed at timestamp `00000000` to apply BEFORE all
-- schema migrations. That ordering caused `supabase start` to fail locally with
-- `ERROR: type "public.members" does not exist (SQLSTATE 42704)` because the
-- RPCs referenced tables (members/events/attendance/gamification_points/
-- board_items/publication_submission_events) that hadn't been created yet.
--
-- p202 (issue #164 path C, 2026-05-19) — the RPC bodies were moved to
-- `20260723000000_baseline_rpcs_after_schema.sql` so they run after the
-- schema migrations have populated the underlying tables.
--
-- This file is preserved (rather than deleted) because production already
-- recorded the migration `00000000_baseline_rpcs` as applied in
-- `supabase_migrations.schema_migrations`. Keeping the file means existing
-- deployments don't see a "missing migration" warning on the next CLI sync.
-- The body intentionally contains no DDL — re-applying the migration is a
-- no-op, and the live RPCs are now sourced from the after-schema file.
--
-- See `docs/operations/LOCAL_QA.md` for the local QA workflow + prerequisite
-- (running `supabase db pull --linked` to seed the schema before
-- `supabase start`).
-- ============================================================================
