UPDATE public.governance_documents SET version='R3-C3-IP-v2.1', status='under_review', updated_at=now()
WHERE id='280c2c56-e0e3-4b10-be68-6c731d1b4520';

INSERT INTO public.document_versions
  (document_id, version_number, version_label, content_html,
   authored_by, authored_at, published_at, published_by, locked_at, locked_by, notes)
VALUES
  ('280c2c56-e0e3-4b10-be68-6c731d1b4520', 1, 'R3-C3-IP-v2.1',
   $html_v21$
<p><strong>Termo de Compromisso de Voluntário</strong></p>
<p>Núcleo de Estudos e Pesquisa em Inteligência Artificial e Gestão de Projetos</p>
<p><em>DRAFT R3-C3-IP v2.1 — Pendente validação jurídica e aprovação CR-050</em></p>
<p>Capítulos: PMI-GO (sede), PMI-CE, PMI-DF, PMI-MG, PMI-RS</p>
<p><strong>Nota de versão:</strong> Este draft incorpora as revisões do CR-050 ao Termo R3-C3 vigente. Alterações principais em relação ao R3-C3-IP v1 (draft anterior): (i) substituição integral da Cláusula 2 por cinco subcláusulas (2.1 a 2.5) com enquadramento jurídico correto para direitos autorais (9.610), software (9.609) e propriedade industrial (9.279); (ii) inclusão da Cláusula 2.6 (publicação externa com exigência de exclusividade) — mecanismo de suspensão temporária da licença; (iii) ressalva na Cláusula 4 para compatibilizar com a Política de Publicação; (iv) inclusão da Cláusula 13 (lei aplicável e jurisdição) para escopo internacional do Programa; (v) correção de referência jurídica (Art. 51 da Lei 9.610, que trata do prazo de cinco anos para cessão de obras futuras — no draft anterior havia referência incorreta ao "Art. 49 §4º").</p>
<p><strong>Nota v2.0 → v2.1 (19/Abr/2026):</strong> Incorporados os ajustes do parecer de auditoria jurídica pré-ratificação: (i) refinamento da Cláusula 2.2.2 para deixar explícito que a suspensão temporária prevista na 2.6 não constitui revogação da licença; (ii) cross-reference da Cláusula 2.4 indicando prevalência da 2.6 para publicações com exigência de exclusividade; (iii) nova Cláusula 2.6.7 — autorização expressa para cessão exclusiva ao publicador durante o período de suspensão; (iv) nova Cláusula 2.6.8 — restabelecimento antecipado da licença em caso de rejeição ou desistência; (v) nota final na Cláusula 2.6 estendendo o mecanismo para casos de incompatibilidade CC-BY-SA → CC-BY; (vi) novo §2 da Cláusula 9 explicitando a posição do VOLUNTÁRIO como titular de dados pessoais perante o PMI-GO como controlador (LGPD Art. 7º V e Art. 18); (vii) parágrafo único da Cláusula 11 sobre revogação do consentimento ao uso de imagem.</p>
<p><strong>Cláusula 1.</strong> O VOLUNTÁRIO declara que está ciente e que aceitou os termos da Lei do Serviço Voluntário, Lei nº 9.608, de 18 de fevereiro de 1998, com redação atualizada pela Lei nº 13.297, de 16 de junho de 2016, anexa a este termo, sendo que:</p>
<ul>
<li><p>(a) O {chapterName} não terá qualquer vínculo trabalhista, previdenciário, fiscal e/ou financeiro com o VOLUNTÁRIO;</p></li>
<li><p>(b) Da mesma forma, qualquer parceiro do {chapterName} que venha a ter atividades desenvolvidas junto ao VOLUNTÁRIO, não terá, por razão destas atividades, qualquer vínculo trabalhista, previdenciário, fiscal e/ou financeiro com o VOLUNTÁRIO;</p></li>
<li><p>(c) O {chapterName} não se obriga a comprar, alugar, instalar, disponibilizar e/ou manter qualquer tipo de equipamento ou sistemas que venham a ser utilizados pelo VOLUNTÁRIO na execução das atividades voluntárias.</p></li>
</ul>
<p>Cláusula 2. Propriedade Intelectual</p>
<p>Os direitos sobre obras intelectuais produzidas pelo VOLUNTÁRIO no âmbito do Programa seguem as regras abaixo:</p>
<p><strong>2.1 Direitos Morais.</strong> O VOLUNTÁRIO retém todos os direitos morais sobre suas obras, incluindo os direitos de paternidade, crédito e integridade, conforme a Lei nº 9.610/1998, Art. 24 a 27, e, quando aplicável, conforme a legislação de direitos morais da jurisdição de residência do VOLUNTÁRIO, reconhecendo-se o padrão mais protetivo ao autor em caso de divergência, nos termos da Convenção de Berna. Esses direitos são inalienáveis e irrenunciáveis.</p>
<p><strong>Parágrafo único.</strong> No caso específico de programa de computador, aplicam-se os direitos morais na extensão prevista pelo art. 2º, §1º, da Lei nº 9.609/1998, que assegura ao VOLUNTÁRIO o direito de reivindicar a paternidade do programa e de opor-se a alterações não autorizadas que impliquem deformação, mutilação ou modificação que prejudiquem sua honra ou reputação.</p>
<p><strong>2.2 Licença ao Núcleo.</strong> O VOLUNTÁRIO concede ao Núcleo de Estudos e Pesquisa em IA &amp; GP licença não-exclusiva, gratuita e mundial para reproduzir, distribuir, exibir publicamente, criar obras derivadas e sublicenciar <strong>cada obra</strong> produzida no âmbito do Programa — exclusivamente para fins educacionais e científicos.</p>
<p><strong>2.2.1</strong> A licença prevista no caput é outorgada <strong>no momento da entrega ou publicação interna de cada obra específica</strong> e vigorará pelo prazo de proteção legal da obra aplicável em cada jurisdição, não caracterizando cessão de obras futuras em bloco, nos termos do art. 51 da Lei nº 9.610/1998.</p>
<p><strong>2.2.2</strong> A licença é <strong>não-revogável unilateralmente pelo VOLUNTÁRIO após a sua outorga por obra específica</strong>, ressalvada a suspensão temporária prevista na Cláusula 2.6 (Publicação Externa com Exigência de Exclusividade), que não constitui revogação da licença mas regime transitório de não-exercício pelo Núcleo, e as hipóteses legais de resolução contratual.</p>
<p><strong>2.3 Direito de Publicação.</strong> O VOLUNTÁRIO mantém o direito de publicar individualmente ou em coautoria as obras produzidas, desde que inclua atribuição ao Núcleo conforme a Política de Publicação e Propriedade Intelectual vigente.</p>
<p><strong>2.4 Notificação.</strong> Publicações externas de obras produzidas no Programa requerem notificação prévia ao Gerente de Projeto com 15 (quinze) dias de antecedência, exceto para conteúdo classificado como confidencial (Cláusula 9). O GP pode solicitar revisão, mas não pode vetar publicação de conteúdo Track A (Aberto). Quando a publicação externa envolver exigência de exclusividade pelo publicador, aplicam-se adicionalmente os procedimentos da Cláusula 2.6, que prevalece sobre esta Cláusula no que for específico.</p>
<p><strong>2.5 Enquadramento Jurídico das Obras.</strong> Os direitos sobre as obras produzidas pelo VOLUNTÁRIO no âmbito do Programa seguem o enquadramento legal aplicável à natureza de cada obra:</p>
<p><strong>2.5.1 Obras literárias, científicas, artísticas, frameworks, metodologias, templates e documentos em geral</strong> são protegidos como direitos autorais, nos termos da Lei nº 9.610/1998, independentemente de registro (art. 18 da Lei nº 9.610/1998).</p>
<p><strong>2.5.2 Programas de computador</strong> (códigos-fonte e objeto) são protegidos pelo regime de direitos autorais, nos termos da Lei nº 9.609/1998, observadas as especificidades do art. 2º, §1º, quanto aos direitos morais (Cláusula 2.1, parágrafo único, deste Termo).</p>
<p><strong>2.5.3 Invenções, modelos de utilidade, desenhos industriais e marcas</strong> passíveis de proteção industrial seguem a Lei nº 9.279/1996. A avaliação de patenteabilidade ou registrabilidade deve preceder qualquer divulgação pública, sob pena de perda da novidade exigida pelo art. 11 da Lei nº 9.279/1996. O fluxo de análise, aprovação, titularidade, custeio e política de exploração segue o disposto na Seção 4 da Política de Publicação e Propriedade Intelectual.</p>
<p><strong>2.5.4 Registros internacionais</strong> equivalentes em jurisdições estrangeiras observam os tratados vigentes no Brasil e a Seção 4.6 da Política de Publicação.</p>
<p><strong>2.6 Publicação Externa com Exigência de Exclusividade.</strong> Caso o VOLUNTÁRIO pretenda submeter obra produzida no âmbito do Programa a periódico científico, editora ou evento que exija, como condição de aceitação, cessão exclusiva de direitos patrimoniais ou ineditismo da obra, aplica-se o seguinte procedimento:</p>
<p><strong>2.6.1</strong> O VOLUNTÁRIO notificará o Gerente de Projeto com antecedência mínima de 15 (quinze) dias, indicando: (a) a obra objeto da publicação; (b) o periódico, editora ou evento de destino; (c) a política editorial exigida (exclusividade, cessão, ineditismo); (d) o prazo estimado de embargo editorial.</p>
<p><strong>2.6.2</strong> Mediante a notificação, a licença concedida ao Núcleo sobre aquela obra específica entra em <strong>regime de suspensão temporária (<em><strong>standby</strong></em>)</strong> pelo prazo necessário ao cumprimento das exigências editoriais, não excedendo 24 (vinte e quatro) meses renováveis por igual período mediante nova notificação.</p>
<p><strong>2.6.3</strong> Durante o período de suspensão, o Núcleo compromete-se a não publicar, distribuir ou criar obras derivadas daquela obra específica, preservando-se, contudo, os direitos do Núcleo sobre obras anteriores, simultâneas ou derivadas já em circulação.</p>
<p><strong>2.6.4</strong> Findo o período de exclusividade editorial ou cessando a exigência que a motivou, a licença ao Núcleo é <strong>automaticamente restabelecida</strong> em seus termos originais, devendo o VOLUNTÁRIO comunicar o fim do embargo ao Gerente de Projeto.</p>
<p><strong>2.6.5</strong> O VOLUNTÁRIO obriga-se a incluir, na publicação externa, nota de agradecimento ao Núcleo de Estudos e Pesquisa em IA &amp; GP como origem institucional da pesquisa, na forma mais ampla permitida pela política editorial de destino, ou, caso vedada pelo publicador, a registrar a vinculação ao Núcleo na página de perfil do autor no próprio publicador ou em repositório pessoal de acesso público equivalente.</p>
<p><strong>2.6.6</strong> A suspensão temporária não se aplica a publicações sob Track A (Aberto) da Política de Publicação, que seguem fluxo de notificação simples sem necessidade de standby.</p>
<p><strong>2.6.7 Autorização para cessão exclusiva ao publicador.</strong> Durante o período de suspensão temporária previsto nas subcláusulas anteriores, o VOLUNTÁRIO fica autorizado a outorgar ao publicador externo os direitos de exclusividade exigidos como condição editorial, incluindo cessão exclusiva de direitos patrimoniais sobre a obra específica pelo prazo do embargo. A licença do Núcleo, embora não extinta, não será exercida nesse período (Cláusula 2.6.3), de modo que a exclusividade concedida ao publicador seja factualmente operante.</p>
<p><strong>2.6.8 Restabelecimento antecipado.</strong> Em caso de rejeição da submissão pelo publicador ou desistência do VOLUNTÁRIO antes do término do prazo de embargo, o VOLUNTÁRIO comunicará imediatamente ao Gerente de Projeto, e a licença ao Núcleo será automaticamente restabelecida na data dessa comunicação, sem aguardar o término do prazo original de suspensão.</p>
<p><strong>2.6.9 Incompatibilidade entre licenças abertas.</strong> O mecanismo desta Cláusula aplica-se também às hipóteses de incompatibilidade de licença aberta entre o Track B (CC-BY-SA 4.0) e a licença exigida pelo publicador externo (CC-BY 4.0 ou equivalente não-SA), mediante autorização específica nos termos da Seção 5 da Política de Publicação e Propriedade Intelectual (Re-licenciamento para periódicos).</p>
<p>Cláusulas Gerais</p>
<p><strong>Cláusula 3.</strong> O VOLUNTÁRIO, por sua vez, tem direito ao reconhecimento oficial de seu trabalho de acordo com as responsabilidades efetivamente assumidas e as tarefas efetivamente executadas.</p>
<p><strong>Cláusula 4.</strong> O VOLUNTÁRIO não poderá emitir conceitos, falar ou utilizar o nome ou documentos do {chapterName} sem a prévia autorização do {chapterName}, ressalvadas as seguintes hipóteses:</p>
<p><strong>Parágrafo único.</strong> Não constitui violação desta cláusula:</p>
<ul>
<li><p>(a) A inclusão de atribuição institucional ao Núcleo de Estudos e Pesquisa em IA &amp; GP e ao capítulo de origem do VOLUNTÁRIO em publicações enquadradas nas Tracks A, B ou C da Política de Publicação, observados os respectivos fluxos de notificação ou aprovação previstos na referida Política;</p></li>
<li><p>(b) A menção institucional ao capítulo em contextos acadêmicos, científicos ou profissionais relacionados às atividades voluntárias do VOLUNTÁRIO no âmbito do Programa, desde que consistente com o Código de Ética do Project Management Institute;</p></li>
<li><p>(c) As demais hipóteses expressamente previstas na Política de Publicação e Propriedade Intelectual vigente.</p></li>
</ul>
<p><strong>Cláusula 5.</strong> O VOLUNTÁRIO deverá agir sempre em conformidade com as políticas e os padrões éticos e procedimentais do PMI, e seguir todas as normas internas e do ordenamento jurídico aplicável quando do exercício de suas atividades.</p>
<p><strong>Cláusula 6.</strong> A rescisão do compromisso do VOLUNTÁRIO com o {chapterName} pode ser feita em qualquer tempo, e sem qualquer ônus para ambas as partes.</p>
<p><strong>Cláusula 7.</strong> O VOLUNTÁRIO poderá ser ressarcido pelas despesas que comprovadamente realizar no desempenho das atividades voluntárias, desde que previamente autorizadas pelo {chapterName} e conforme políticas do {chapterName} em vigor.</p>
<p><strong>Parágrafo único —</strong> As despesas a serem ressarcidas deverão estar expressamente autorizadas pela entidade a que for prestado o serviço voluntário.</p>
<p><strong>Cláusula 8.</strong> O presente Termo tem validade indeterminada ou até o rompimento conforme disposto na Cláusula 6.</p>
<p><strong>Cláusula 9. Confidencialidade e LGPD.</strong> A Lei Geral de Proteção de Dados Pessoais — Lei nº 13.709, de 14 de agosto de 2018 (LGPD) — dispõe que quaisquer dados de terceiros e/ou informações pessoais que possam ser obtidas ou utilizadas por qualquer das partes em decorrência do presente contrato, serão recolhidos, utilizados, armazenados e mantidos de acordo com os padrões geralmente aceitos para coleta de dados e pela legislação aplicável. O VOLUNTÁRIO se obriga a:</p>
<ul>
<li><p>(a) Tratar os dados conforme sua necessidade ou obrigatoriedade, respeitando os princípios da finalidade, adequação, transparência, livre acesso, segurança, prevenção e não discriminação;</p></li>
<li><p>(b) Manter sigilo de todos os dados, informações científicas e técnicas obtidas por meio da prestação de serviço voluntário;</p></li>
<li><p>(c) Não revelar, reproduzir ou dar conhecimento a terceiros de dados, informações ou materiais obtidos;</p></li>
<li><p>(d) Não tomar qualquer medida com vistas a obter para si ou para terceiros os direitos de propriedade intelectual relativos às informações sigilosas a que tenha acesso;</p></li>
<li><p>(e) Utilizar as informações confidenciais apenas com o propósito de cumprir com os fins do programa voluntário;</p></li>
<li><p>(f) Manter procedimentos adequados à prevenção de extravios ou perda de documentos ou informações confidenciais.</p></li>
</ul>
<p><strong>§ 1º</strong> O {chapterName} não disponibiliza informações para bancos de dados, empresas ou associações. O Encarregado pela Proteção de Dados Pessoais (DPO) designado pelo PMI-GO atua como ponto focal para o Núcleo, nos termos da Seção 2 da Política de Publicação e Propriedade Intelectual.</p>
<p><strong>§ 2º Direitos do VOLUNTÁRIO como titular de dados pessoais.</strong> O PMI Brasil–Goiás Chapter (PMI-GO), na condição de controlador, trata os dados pessoais do próprio VOLUNTÁRIO para fins de execução deste Termo, tendo como base legal o art. 7º, V, da Lei nº 13.709/2018 (LGPD — execução de contrato). O VOLUNTÁRIO, na qualidade de titular, tem direito de acesso, retificação, eliminação, portabilidade e revogação de consentimento referentes aos seus dados pessoais, exercíveis junto ao Encarregado designado pelo PMI-GO, na forma da Seção 2 da Política de Publicação e Propriedade Intelectual e dos arts. 17 e 18 da LGPD. Os dados pessoais do VOLUNTÁRIO serão retidos pelo prazo de vigência deste Termo, acrescido de 5 (cinco) anos após seu encerramento para fins de cumprimento de obrigações legais e prestação de contas institucionais, conforme a Política de Privacidade do PMI-GO.</p>
<p><strong>Cláusula 10.</strong> O presente Termo estabelece e consolida as obrigações do VOLUNTÁRIO relativas à confidencialidade, ao sigilo de informações e à proteção de dados pessoais, nos termos da Lei nº 13.709/2018 (LGPD), sendo suficiente para reger tais matérias no âmbito do programa de voluntariado.</p>
<p><strong>Cláusula 11.</strong> Ao assinar este Termo o VOLUNTÁRIO autoriza a utilização de fotos ou imagens profissionais captadas em evento para divulgação e promoção do trabalho voluntário.</p>
<p><strong>Parágrafo único.</strong> O VOLUNTÁRIO poderá revogar a autorização prevista nesta Cláusula a qualquer tempo, mediante comunicação ao Gerente de Projeto ou ao Encarregado do PMI-GO, sem efeito retroativo sobre usos já realizados, nos termos do art. 8º, §5º, da Lei nº 13.709/2018.</p>
<p><strong>Cláusula 12.</strong> Não se estabelece entre as partes qualquer forma de sociedade, associação, mandato, representação, agência, consórcio ou responsabilidade solidária.</p>
<p>Cláusula 13. Lei Aplicável e Jurisdição</p>
<p><strong>13.1</strong> Este Termo é regido pela legislação brasileira, em especial pelas Leis nº 9.608/1998, nº 9.609/1998, nº 9.610/1998, nº 9.279/1996 e nº 13.709/2018, bem como pelo Código de Ética do Project Management Institute e pelos tratados internacionais de propriedade intelectual vigentes no Brasil.</p>
<p><strong>13.2</strong> Para VOLUNTÁRIOS residentes fora do Brasil, aplica-se a legislação brasileira, observado o princípio do tratamento nacional da Convenção de Berna, preservando-se os direitos morais do VOLUNTÁRIO no padrão mais protetivo entre a legislação brasileira e a legislação da jurisdição de sua residência.</p>
<p><strong>13.3</strong> Controvérsias decorrentes deste Termo seguem o disposto na Seção 1.7 da Política de Publicação e Propriedade Intelectual do Núcleo.</p>
<p><em>Draft R3-C3-IP v2.1 | CR-050 | Núcleo de Estudos e Pesquisa em IA &amp; GP</em></p>
<p><em>Alterações em relação ao R3-C3 (termo vigente): Cláusula 2 integralmente substituída; Cláusula 4 com parágrafo único de ressalvas; Cláusula 9 com atualização do Encarregado e §2 novo (direitos do voluntário como titular LGPD); Cláusula 11 com parágrafo único (revogação consentimento imagem); Cláusula 13 incluída.</em></p>
$html_v21$,
   '880f736c-3e76-4df4-9375-33575c190305', now(), now(), '880f736c-3e76-4df4-9375-33575c190305', now(), '880f736c-3e76-4df4-9375-33575c190305',
   'Seed Phase IP-1 v2.1 pos-auditoria juridica 19/Abr/2026 (Termo Ciclo 4)');

INSERT INTO public.approval_chains
  (document_id, version_id, status, gates, opened_at, opened_by, notes)
SELECT '280c2c56-e0e3-4b10-be68-6c731d1b4520', id, 'review',
  '[{"kind":"curator","threshold":1,"order":1},{"kind":"leader","threshold":1,"order":2},{"kind":"president_go","threshold":1,"order":3},{"kind":"president_others","threshold":4,"order":4},{"kind":"member_ratification","threshold":"all","order":5}]'::jsonb,
  now(), '880f736c-3e76-4df4-9375-33575c190305', 'Chain aberto pos-auditoria juridica 19/Abr/2026'
FROM public.document_versions
WHERE document_id='280c2c56-e0e3-4b10-be68-6c731d1b4520' AND version_label='R3-C3-IP-v2.1'
ON CONFLICT (document_id, version_id) DO NOTHING;
