// supabase/functions/analyze-application-video/index.ts
//
// p197d D1 (2026-05-19): video AI analysis pipeline. For each uploaded pmi_video_screening
// row of an application, generates a suggestion in selection_evaluation_ai_suggestions
// (evaluation_type='video', suggested_scores keyed by pillar).
//
// Flow per pillar:
//   1. Resolve Google Drive file_id from pmi_video_screenings.drive_file_id
//   2. Transcribe via OpenAI Whisper (multipart/form-data, audio extraction handled by Whisper)
//   3. Fetch Drive thumbnail (auto-generated by Drive for video files)
//   4. Claude Haiku 4.5 multimodal: transcription + thumbnail + cycle rubric → {score, reasoning}
//   5. Persist transcription to pmi_video_screenings + insert ai_suggestion
//
// Auth: service_role only (called by trigger via pg_net OR public analyze_application_video RPC).
// Idempotency: skip if pending suggestion exists for (application_id, pillar) unless force=true.
// LGPD: consent_ai_analysis_at gate (re-verified here in case state changed since dispatch).
// Cost guard: skip Whisper if video > 25MB (OpenAI limit). Falls back to thumbnail-only analysis.
//
// Decisions ratified p197d D1 (PM 2026-05-19):
// - Whisper API (multilingue, robusto)
// - Híbrido transcription + 1 frame (Drive thumbnail)
// - Score por pillar (5 pillars: background + 4 matching interview rubric)
// - Claude Haiku 4.5 multimodal
//
// Graceful degradation:
// - OPENAI_API_KEY missing → skip Whisper, use existing pmi_video_screenings.transcription or "(no transcription)"
// - Drive thumbnail unreachable → text-only analysis
// - Claude error → log + skip pillar
//
// p199-a hotfix (2026-05-19 post-quota re-smoke): include organization_id explicitly
// in selection_evaluation_ai_suggestions INSERT. Table default is auth_org() which
// returns NULL under service_role (no auth.uid()), causing NOT NULL violation
// observed in re-smoke (ai_processing_log row 5414b444 — Whisper+Claude succeeded
// 20.8s, only the final insert failed). Pulled from app.organization_id (NOT NULL
// on selection_applications). ai_processing_log has a hardcoded org_id default so
// is unaffected — asymmetric design preserved intentionally.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const WHISPER_MAX_BYTES = 25 * 1024 * 1024; // 25 MB OpenAI limit
const FETCH_TIMEOUT_MS = 60_000;
const CLAUDE_MODEL = "claude-haiku-4-5-20251001";

// Interview rubric guide-lines reused for video pillars where they match.
// background is video-only (extra signal, doesn't sum to interview score).
const PILLAR_GUIDES: Record<string, string> = {
  background: "Trajetória profissional clara + diversidade de experiências + storytelling estruturado. 0-2 vago / 3-4 trajetória básica / 5-6 conectada com GP+IA / 7-8 narrativa coesa com marcos concretos / 9-10 trajetória excepcional com impacto demonstrado.",
  communication: "0-2 dificuldade de articulação / 3-4 ideias básicas sem clareza técnica / 5-6 clareza razoável / 7-8 articula ideias complexas com clareza / 9-10 excepcional, escuta ativa, exemplos concretos.",
  proactivity: "0-2 reativo / 3-4 exemplos vagos / 5-6 iniciativa em situações específicas / 7-8 histórico de propor soluções / 9-10 líder natural com impacto mensurável.",
  teamwork: "0-2 prefere trabalho individual / 3-4 colabora sob solicitação / 5-6 bom colaborador / 7-8 colaboração efetiva em times diversos / 9-10 catalisador de equipe.",
  culture_alignment: "0-2 sem conhecimento valores PMI / 3-4 superficial / 5-6 conhece Código de Ética + propósito do Núcleo / 7-8 valores alinhados com postura ética consistente / 9-10 embaixador natural — integridade como segunda natureza.",
};

interface VideoRow {
  id: string;
  application_id: string;
  pillar: string;
  question_index: number;
  question_text: string;
  status: string;
  drive_file_id: string | null;
  youtube_url: string | null;
  transcription: string | null;
  file_size_bytes: number | null;
}

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
}

// p197d D1: use OAuth user-delegated refresh_token flow (same pattern as
// pmi-video-test-transcribe, drive-upload-to-folder, etc). Service account JWT was
// initial attempt but the SA email doesn't have access to candidate-uploaded folders;
// OAuth user-delegated does, since the upload itself happened with these credentials.
async function getDriveAccessToken(sb: ReturnType<typeof createClient>): Promise<string> {
  const credsStr = await getVaultSecret(sb, "google_drive_oauth_credentials");
  if (!credsStr) throw new Error("google_drive_oauth_credentials not in vault");
  const creds = JSON.parse(credsStr) as { client_id: string; client_secret: string; refresh_token: string };
  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: creds.client_id,
      client_secret: creds.client_secret,
      refresh_token: creds.refresh_token,
      grant_type: "refresh_token",
    }),
  });
  if (!res.ok) throw new Error(`drive_oauth_refresh_failed_${res.status}_${(await res.text()).slice(0, 150)}`);
  const { access_token } = await res.json();
  return access_token;
}

async function driveDownloadVideo(fileId: string, accessToken: string): Promise<{ bytes: Uint8Array; size: number; mime: string }> {
  const metaRes = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?fields=size,mimeType,name&supportsAllDrives=true`, {
    headers: { authorization: `Bearer ${accessToken}` },
  });
  if (!metaRes.ok) throw new Error(`drive_meta_failed_${metaRes.status}_${(await metaRes.text()).slice(0, 100)}`);
  const meta = await metaRes.json();
  const size = parseInt(meta.size ?? "0", 10);
  const mime = meta.mimeType ?? "video/mp4";

  if (size > WHISPER_MAX_BYTES) {
    throw new Error(`video_too_large_${size}_bytes_max_${WHISPER_MAX_BYTES}`);
  }

  const dlRes = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media&supportsAllDrives=true`, {
    headers: { authorization: `Bearer ${accessToken}` },
  });
  if (!dlRes.ok) throw new Error(`drive_download_failed_${dlRes.status}`);
  const bytes = new Uint8Array(await dlRes.arrayBuffer());
  return { bytes, size, mime };
}

async function driveGetThumbnailBytes(fileId: string, accessToken: string): Promise<{ bytes: Uint8Array; mime: string } | null> {
  const metaRes = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?fields=thumbnailLink&supportsAllDrives=true`, {
    headers: { authorization: `Bearer ${accessToken}` },
  });
  if (!metaRes.ok) return null;
  const { thumbnailLink } = await metaRes.json();
  if (!thumbnailLink) return null;
  const upscaled = thumbnailLink.replace(/=s\d+$/, "=s800");
  const tnRes = await fetch(upscaled, { headers: { authorization: `Bearer ${accessToken}` } });
  if (!tnRes.ok) return null;
  return { bytes: new Uint8Array(await tnRes.arrayBuffer()), mime: tnRes.headers.get("content-type") ?? "image/jpeg" };
}

async function whisperTranscribe(videoBytes: Uint8Array, mime: string, openaiKey: string): Promise<string> {
  const form = new FormData();
  form.append("file", new Blob([videoBytes], { type: mime }), `video.${mime.split("/")[1] ?? "mp4"}`);
  form.append("model", "whisper-1");
  form.append("language", "pt"); // PT-BR primary; Whisper auto-detects but seeding helps
  form.append("response_format", "text");

  const res = await fetch("https://api.openai.com/v1/audio/transcriptions", {
    method: "POST",
    headers: { authorization: `Bearer ${openaiKey}` },
    body: form,
  });
  if (!res.ok) {
    const errBody = await res.text();
    throw new Error(`whisper_failed_${res.status}_${errBody.slice(0, 200)}`);
  }
  return (await res.text()).trim();
}

async function claudeAnalyzePillar(args: {
  anthropicKey: string;
  pillar: string;
  questionText: string;
  transcription: string;
  thumbnailB64: string | null;
  thumbnailMime: string | null;
  applicantName: string;
}): Promise<{ score: number; reasoning: string; criterion_notes: string }> {
  const guide = PILLAR_GUIDES[args.pillar] ?? "Avalie 0-10 baseado em conteúdo do vídeo e transcrição.";
  const system = `Você é avaliador imparcial de candidatos a voluntariado do Núcleo IA & GP (comunidade PMI Brasil). Avalie o pilar "${args.pillar}" do vídeo do candidato em escala 0-10 conforme rubric. LGPD Art. 20: sua análise é NÃO-VINCULANTE — humano evaluator decide final. Responda em JSON exato {"score": número 0-10, "reasoning": "1-2 sentenças do porquê", "criterion_notes": "feedback construtivo 1-2 sentenças que o evaluator humano usaria"}.`;

  const userParts: any[] = [{
    type: "text",
    text: `Pilar: **${args.pillar}**\nPergunta ao candidato: "${args.questionText}"\nCandidato: ${args.applicantName}\n\nRubric (escala 0-10):\n${guide}\n\nTranscrição do vídeo:\n${args.transcription || "(transcrição indisponível)"}\n\nAvalie o pilar.`
  }];
  if (args.thumbnailB64 && args.thumbnailMime) {
    userParts.unshift({
      type: "image",
      source: { type: "base64", media_type: args.thumbnailMime, data: args.thumbnailB64 }
    });
  }

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": args.anthropicKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 400,
      system,
      messages: [{ role: "user", content: userParts }],
    }),
  });
  if (!res.ok) throw new Error(`claude_failed_${res.status}_${(await res.text()).slice(0, 200)}`);
  const data = await res.json();
  const text = (data.content?.[0]?.text ?? "").trim();
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error(`claude_no_json_${text.slice(0, 100)}`);
  const parsed = JSON.parse(jsonMatch[0]);
  return {
    score: Math.max(0, Math.min(10, Number(parsed.score) || 0)),
    reasoning: String(parsed.reasoning ?? "").slice(0, 1000),
    criterion_notes: String(parsed.criterion_notes ?? "").slice(0, 1000),
  };
}

async function getVaultSecret(sb: ReturnType<typeof createClient>, name: string): Promise<string | null> {
  const { data, error } = await sb.rpc("_get_vault_secret", { p_name: name });
  if (error) {
    console.warn(`vault_secret_${name}_failed:`, error.message);
    return null;
  }
  return (data as string) || null;
}

// p197d D1 (2026-05-19): processVideos is the slow part — extracted into a separate async
// function so the request handler can return 200 immediately (pg_net default timeout = 5s,
// but Whisper+Drive download is 10-30s per pillar). EdgeRuntime.waitUntil keeps the
// runtime alive until the work finishes (Deno Edge Functions supports it).
async function processVideosBackground(
  sb: ReturnType<typeof createClient>,
  application_id: string,
  pillar: string | null,
  triggeredBy: string,
) {
  try {
    const { data: app, error: appErr } = await sb
      .from("selection_applications")
      .select("id, applicant_name, cycle_id, organization_id, consent_ai_analysis_at, consent_ai_analysis_revoked_at")
      .eq("id", application_id).single();
    if (appErr || !app) { console.error("app_not_found:", appErr?.message); return; }
    if (!app.consent_ai_analysis_at || app.consent_ai_analysis_revoked_at) {
      console.log("consent_pending_or_revoked, skipping:", application_id); return;
    }

    const videoQuery = sb.from("pmi_video_screenings")
      .select("id, application_id, pillar, question_index, question_text, status, drive_file_id, youtube_url, transcription, file_size_bytes")
      .eq("application_id", application_id).eq("status", "uploaded");
    const { data: videoRows, error: vErr } = pillar
      ? await videoQuery.eq("pillar", pillar) : await videoQuery;
    if (vErr) { console.error("video_query_failed:", vErr.message); return; }
    if (!videoRows || videoRows.length === 0) { console.log("no_uploaded_videos:", application_id); return; }

    const openaiKey = await getVaultSecret(sb, "openai_api_key");
    const anthropicKey = await getVaultSecret(sb, "anthropic_api_key");
    let driveToken: string | null = null;
    try { driveToken = await getDriveAccessToken(sb); }
    catch (e) { console.error("drive_oauth_failed:", (e as Error).message); }

    for (const v of videoRows as VideoRow[]) {
      const t0 = Date.now();
      let logId: string | null = null;
      let stage = "init";
      try {
        const { data: logRow } = await sb.from("ai_processing_log").insert({
          application_id, model_provider: "anthropic", model_id: CLAUDE_MODEL,
          purpose: "video_screening", triggered_by: triggeredBy, status: "running",
        }).select("id").single();
        logId = logRow?.id ?? null;

        if (!v.drive_file_id) { console.log("no_drive_file_id:", v.id); continue; }
        if (!driveToken) { console.log("drive_oauth_unavailable for", v.id); continue; }

        let transcription = v.transcription ?? "";
        let transcribedNow = false;
        if (!transcription && openaiKey) {
          stage = "drive_download";
          const { bytes, mime } = await driveDownloadVideo(v.drive_file_id, driveToken);
          stage = "whisper";
          transcription = await whisperTranscribe(bytes, mime, openaiKey);
          transcribedNow = true;
          await sb.from("pmi_video_screenings").update({
            transcription, transcription_provider: "openai",
            transcription_model_version: "whisper-1",
            transcription_at: new Date().toISOString(),
          }).eq("id", v.id);
        } else if (!transcription && !openaiKey) {
          console.log("openai_key_missing for", v.id); continue;
        }

        stage = "thumbnail";
        let thumbnailB64: string | null = null;
        let thumbnailMime: string | null = null;
        const tn = await driveGetThumbnailBytes(v.drive_file_id, driveToken);
        if (tn) {
          thumbnailB64 = btoa(String.fromCharCode(...tn.bytes));
          thumbnailMime = tn.mime;
        }

        if (!anthropicKey) { console.log("anthropic_key_missing for", v.id); continue; }
        stage = "claude";
        const analysis = await claudeAnalyzePillar({
          anthropicKey, pillar: v.pillar, questionText: v.question_text,
          transcription, thumbnailB64, thumbnailMime, applicantName: app.applicant_name,
        });

        stage = "suggestion_insert";
        // organization_id explicit — table default auth_org() returns NULL under
        // service_role (no auth.uid()), causing NOT NULL violation. Pull from
        // selection_applications.organization_id (NOT NULL) for tenant alignment.
        const { error: sugErr } = await sb.from("selection_evaluation_ai_suggestions").insert({
          application_id, organization_id: app.organization_id,
          evaluation_type: "video",
          suggested_scores: { [v.pillar]: analysis.score },
          suggested_criterion_notes: { [v.pillar]: analysis.criterion_notes },
          suggested_overall_summary: analysis.reasoning,
          suggested_weighted_subtotal: analysis.score,
          model_provider: "anthropic", model_name: CLAUDE_MODEL,
          prompt_version: "p197d_d1_v1",
          generation_inputs: {
            pillar: v.pillar, question_text: v.question_text,
            transcription_chars: transcription.length,
            has_thumbnail: !!thumbnailB64,
            video_screening_id: v.id,
          },
          consent_snapshot_at: app.consent_ai_analysis_at,
        });
        if (sugErr) throw new Error(`suggestion_insert_failed: ${sugErr.message}`);

        if (logId) {
          await sb.from("ai_processing_log").update({
            status: "completed", duration_ms: Date.now() - t0,
            completed_at: new Date().toISOString(),
          }).eq("id", logId);
        }
        console.log(`ok pillar=${v.pillar} score=${analysis.score} transcribed_now=${transcribedNow}`);
      } catch (e) {
        const errMsg = (e as Error).message;
        if (logId) {
          await sb.from("ai_processing_log").update({
            status: "failed", duration_ms: Date.now() - t0,
            error_message: `${stage}: ${errMsg}`,
            completed_at: new Date().toISOString(),
          }).eq("id", logId);
        }
        console.error(`pillar=${v.pillar} stage=${stage} error=${errMsg}`);
      }
    }
  } catch (e) {
    console.error("processVideosBackground fatal:", (e as Error).message);
  }
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: {
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "POST, OPTIONS",
      "access-control-allow-headers": "authorization, content-type",
    }});
  }
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);

  const authHeader = req.headers.get("authorization") ?? "";
  const token = authHeader.replace(/^Bearer\s+/i, "");
  try {
    const payload = JSON.parse(atob(token.split(".")[1].replace(/-/g, "+").replace(/_/g, "/")));
    if (payload.role !== "service_role") {
      return json({ error: "unauthorized_service_role_only", got: payload.role ?? "no_role" }, 401);
    }
  } catch (_) {
    return json({ error: "invalid_jwt" }, 401);
  }

  const body = await req.json().catch(() => ({}));
  const { application_id, pillar, force, triggered_by } = body ?? {};
  if (!application_id) return json({ error: "missing_application_id" }, 400);

  const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
  const triggeredBy = typeof triggered_by === "string" ? triggered_by : "service_role";

  // Return 200 immediately so pg_net doesn't time out (default 5s). Slow work runs in background.
  // @ts-ignore EdgeRuntime is provided by Supabase Edge Functions runtime
  if (typeof EdgeRuntime !== "undefined" && EdgeRuntime.waitUntil) {
    // @ts-ignore
    EdgeRuntime.waitUntil(processVideosBackground(sb, application_id, pillar ?? null, triggeredBy));
  } else {
    // Local dev fallback: fire-and-forget without waitUntil (Deno still completes pending promises)
    processVideosBackground(sb, application_id, pillar ?? null, triggeredBy);
  }
  return json({ accepted: true, application_id, pillar: pillar ?? "all", async: true }, 202);
});

